const GET_BIKE = "GET_BIKE";
const GET_ORIGIN = "GET_ORIGIN";
const GET_DESTINATION = "GET_DESTINATION";
const GET_DIRECTION = "GET_DIRECTION";
const GET_TRAVEL_MODE = "GET_TRAVEL_MODE";
const GET_DISTANCE = "GET_DISTANCE";
const GET_DURATION = "GET_DURATION";
const GET_MAP_REFERENCE = "GET_MAP_REFERENCE";
const RESET = "RESET"

export {
    GET_BIKE,
    GET_ORIGIN,
    GET_DESTINATION,
    GET_DIRECTION,
    GET_TRAVEL_MODE,
    GET_DISTANCE,
    GET_DURATION,
    GET_MAP_REFERENCE,
    RESET
};
